# Generated by Django 5.2.6 on 2025-09-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_contact_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
